version: "3.8"
services:
  sql:
    build:
      context: ./sql
      dockerfile: Dockerfile
    container_name: scanner_sql
    environment:
      - PORT=5000
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - scanner-net
    volumes:
      - ./sql/results:/app/results     # optional: access sql raw outputs

  xss:
    build:
      context: ./xss
      dockerfile: Dockerfile
    container_name: scanner_xss
    environment:
      - PORT=6000
    expose:
      - "6000"
    restart: unless-stopped
    networks:
      - scanner-net
    volumes:
      - ./xss/xss_results:/app/xss_results  # optional

  nginx:
    image: nginx:stable-alpine
    container_name: scanner_nginx
    ports:
      - "80:80"            # public endpoint
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./sql/results:/data/sql_results:ro   # optional, if you want nginx to serve results
      - ./xss/xss_results:/data/xss_results:ro
    depends_on:
      - sql
      - xss
    restart: unless-stopped
    networks:
      - scanner-net

networks:
  scanner-net:
    driver: bridge
